name: dekt
services:
  postgres:
    image: postgres
    restart: unless-stopped
    platform: linux/amd64
    container_name: dekt-postgres
    environment:
      - POSTGRES_DB=dekt
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD

    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app", "-d", "dekt"]
      interval: 5s
      timeout: 2s
      retries: 20
  app:
    container_name: dekt-app
    restart: unless-stopped
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - astraliskye/dekt:latest
    env_file: .env
    environment:
      - DATABASE_URL
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
    ports:
      - 8888:3000
    depends_on:
      - postgres
volumes:
  pgdata:
