name: dekt
services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    container_name: "dekt-postgres"
    environment:
      POSTGRES_DB: dekt
      POSTGRES_USER: app
      POSTGRES_PASSWORD: hike
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app", "-d", "dekt"]
      interval: 5s
      timeout: 2s
      retries: 20

  app:
    container_name: "dekt-app"
    env_file: .env
    build:
      context: .
      tags:
        - "astraliskye/dekt:latest"
    ports:
      - "8888:3000"
    depends_on:
      - db
volumes:
  dbdata:
