import { type NextPage } from "next";
import Head from "next/head";
import DeckBuilder from "../components/DeckBuilder";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DEKT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <DeckBuilder />
      </main>
    </>
  );
};

export default Home;
