name: Scan for Secrets
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  scan_secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
