name: Test Build
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
        package-manager-cache: false
    - run: npm ci
    - run: npm audit --audit-level=high
    - run: npm run lint:ci
    - run: npm run build
