name: Test Project Build
on:
  pull_request:
    branches:
      - main
jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependendies
        run: npm ci --production
      - name: Setup docker build
        uses: docker/setup-buildx-action@v3
      - name: Run docker build
        run: docker build -t astraliskye/dekt .
